/**
 * Заказчики с несколькими проектами — для фильтра каталога.
 */
(function () {
  window.DCE_CLIENTS = {
    mggt: {
      name: "ГБУ «Мосгоргеотрест»",
      shortName: "Мосгоргеотрест",
      lead: "Совместные проекты в&nbsp;области информационной безопасности, развития ИТ-инфраструктуры и&nbsp;передачи данных.",
      place: "Москва",
    },
    rdi: {
      name: "ФКУ «Росдоринформсвязь»",
      shortName: "Росдоринформсвязь",
      lead: "Долгосрочное сотрудничество по&nbsp;развитию, сопровождению и&nbsp;защите информационных систем федерального масштаба.",
      place: "Москва",
    },
    linsm: {
      name: "ООО «ЛИНС-М»",
      shortName: "ЛИНС-М",
      lead: "Проекты по&nbsp;периметральной безопасности, облачной инфраструктуре и&nbsp;платформам мониторинга.",
      place: "Москва и регионы",
    },
    rgb: {
      name: "ФГБУ «РГБ»",
      shortName: "РГБ",
      lead: "Поддержка и&nbsp;развитие серверной и&nbsp;сетевой инфраструктуры библиотеки.",
      place: "Москва",
    },
    rnpk: {
      name: "АО «РНПК»",
      shortName: "РНПК",
      lead: "Миграция рабочих мест и&nbsp;прикладного ПО&nbsp;на&nbsp;отечественные операционные системы.",
      place: "Москва",
    },
    soees: {
      name: "АО «СО ЕЭС»",
      shortName: "СО ЕЭС",
      lead: "Создание и&nbsp;внедрение корпоративной почтовой инфраструктуры на&nbsp;объектах пилотной зоны.",
      place: "Москва",
    },
    saratovnpz: {
      name: "ПАО «Саратовский НПЗ»",
      shortName: "Саратовский НПЗ",
      lead: "Сопровождение и&nbsp;развитие инфраструктуры двух центров обработки данных.",
      place: "Саратов",
    },
    minenergo: {
      name: "Министерство энергетики Российской Федерации",
      shortName: "Минэнерго России",
      lead: "Импортозамещение, виртуализация и&nbsp;миграция рабочих сред на&nbsp;отечественные платформы.",
      place: "Москва",
    },
  };

  window.DCE_PROJECTS = [
    {
      client: "rdi",
      yearGroup: "2024–2026",
      clientName: "ФКУ «Росдоринформсвязь»",
      desc: "Обеспечение непрерывности и&nbsp;развития информационных систем",
      meta: "Москва · 2024–2025",
      href: "project-rdi.html",
      image: "images/project_02.png",
      imageFit: "contain",
    },
    {
      client: "mggt",
      yearGroup: "2024–2026",
      clientName: "ГБУ «Мосгоргеотрест»",
      desc: "Внедрение многофакторной аутентификации",
      meta: "Москва · 2024–2025",
      href: "project-mggt.html",
      image: "images/project_03.png",
      imageFit: "contain",
    },
    {
      client: "saratovnpz",
      yearGroup: "2024–2026",
      clientName: "ПАО «Саратовский НПЗ»",
      desc: "Поддержка двух ЦОД: Huawei OceanStor, HPE, Fujitsu, Dell, Cisco",
      meta: "Саратов · 2024–2027",
      href: "project-saratovnpz.html",
      image: "images/project_09.png",
      imageFit: "contain",
    },
    {
      client: "rgb",
      yearGroup: "2024–2026",
      clientName: "ФГБУ «РГБ»",
      desc: "Поддержка NEC, EMC, Cisco, HPE: СХД, серверы, коммутаторы, ленточные библиотеки",
      meta: "Москва · 2024–2025",
      href: "project-rgb.html",
      image: "images/project_12.png",
      imageFit: "contain",
    },
    {
      client: "mggt",
      yearGroup: "2024–2026",
      clientName: "ГБУ «Мосгоргеотрест»",
      desc: "Обследование и&nbsp;проектирование инфраструктуры передачи данных",
      meta: "Москва · 2025",
      href: "project-mggt-spd.html",
      image: "images/project_15.png",
      imageFit: "contain",
    },
    {
      client: "minenergo",
      yearGroup: "2024–2026",
      clientName: "Министерство энергетики Российской Федерации",
      desc: "Миграция каталога и&nbsp;рабочих станций на&nbsp;RED OS",
      meta: "Москва · 2025",
      href: "project-minenergo.html",
      image: "images/project_16.png",
      imageFit: "contain",
    },
    {
      client: "rnpk",
      yearGroup: "2024–2026",
      clientName: "АО «РНПК»",
      desc: "Перевод рабочих мест сотрудников на&nbsp;AstraLinux",
      meta: "Москва · 2025",
      href: "project-rnpk.html",
      image: "images/project_17.png",
      imageFit: "contain",
    },
    {
      client: "rnpk",
      yearGroup: "2024–2026",
      clientName: "АО «РНПК»",
      desc: "Миграция программного обеспечения на&nbsp;AstraLinux с&nbsp;сохранением настроек",
      meta: "Москва · 2024–2025",
      href: "project-rnpk-migration.html",
      image: "images/project_18.png",
      imageFit: "contain",
    },
    {
      client: "soees",
      yearGroup: "2024–2026",
      clientName: "АО «СО ЕЭС»",
      desc: "Работы по&nbsp;созданию и&nbsp;внедрению системы электронной почты на&nbsp;Объектах пилотной зоны Заказчика, включая разработку технического проекта",
      meta: "Москва · 2024",
      href: "project-soees.html",
      image: "images/project_19.png",
      imageFit: "contain",
    },
    {
      client: "soees",
      yearGroup: "2024–2026",
      clientName: "АО «СО ЕЭС»",
      desc: "Внедрение пилотной зоны почтовой системы на&nbsp;уровне объекта",
      meta: "Москва · 2024",
      href: "project-soees-pilot.html",
      image: "images/project_21.png",
      imageFit: "contain",
    },
    {
      client: "rgb",
      yearGroup: "2024–2026",
      clientName: "ФГБУ «РГБ»",
      desc: "Техническое обслуживание серверной инфраструктуры",
      meta: "Москва · 2024",
      href: "project-rgb-support.html",
      image: "images/project_22.png",
      imageFit: "contain",
    },
    {
      client: "linsm",
      yearGroup: "2024–2026",
      clientName: "ООО «ЛИНС-М»",
      desc: "Замена межсетевых экранов в&nbsp;частном облаке (Москва, СПб, Красноярск)",
      meta: "3 города · 2024",
      href: "project-linsm.html",
      image: "images/project_23.png",
      imageFit: "contain",
    },
    {
      client: "saratovnpz",
      yearGroup: "2024–2026",
      clientName: "ПАО «Саратовский НПЗ»",
      desc: "Техническое обслуживание серверного и&nbsp;сетевого оборудования",
      meta: "Саратов · 2024",
      href: "project-saratovnpz-support.html",
      image: "images/project_24.png",
      imageFit: "contain",
    },
    {
      client: "mggt",
      yearGroup: "2021–2023",
      clientName: "ГБУ «Мосгоргеотрест»",
      desc: "Обследование распределённой инфраструктуры, разработка рекомендаций и&nbsp;дорожной карты",
      meta: "Москва · 2023",
      href: "project-mggt-infra.html",
      image: "images/project_26.png",
      imageFit: "contain",
    },
    {
      client: "linsm",
      yearGroup: "2021–2023",
      clientName: "ООО «ЛИНС-М»",
      desc: "Поддержка платформы больших данных Splunk",
      meta: "Москва · 2023",
      href: "project-linsm-splunk.html",
      image: "images/project_27.png",
      imageFit: "contain",
    },
    {
      client: "rdi",
      yearGroup: "2021–2023",
      clientName: "ФКУ «Росдоринформсвязь»",
      desc: "Оптимизация работы антиспам системы согласно актуальным угрозам",
      meta: "Москва · 2023",
      href: "project-rdi-antispam.html",
      image: "images/project_28.png",
      imageFit: "contain",
    },
    {
      client: "minenergo",
      yearGroup: "2021–2023",
      clientName: "Министерство энергетики Российской Федерации",
      desc: "Внедрение импортонезависимой среды виртуализации, миграция файловых серверов и&nbsp;решения ВКС",
      meta: "Москва · 2023",
      href: "project-minenergo-2023.html",
      image: "images/project_29.png",
      imageFit: "contain",
    },
    {
      client: "rdi",
      yearGroup: "2021–2023",
      clientName: "ФКУ «Росдоринформсвязь»",
      desc: "Замена системы резервного копирования для 21&nbsp;ИС без остановки работы",
      meta: "Москва · 2023",
      href: "project-rdi-backup.html",
      image: "images/project_30.png",
      imageFit: "contain",
    },
    {
      client: "linsm",
      yearGroup: "2021–2023",
      clientName: "ООО «ЛИНС-М»",
      desc: "Модернизация системы периметральных средств безопасности на&nbsp;28-ми объектах региональной сети филиалов банка",
      meta: "Москва · 2022",
      href: "project-linsm-perimeter.html",
      image: "images/project_42.png",
      imageFit: "contain",
    },
  ];

  window.getClientProjectCount = function (clientId) {
    if (!clientId || !window.DCE_PROJECTS) return 0;
    var n = 0;
    for (var i = 0; i < window.DCE_PROJECTS.length; i++) {
      if (window.DCE_PROJECTS[i].client === clientId) n++;
    }
    return n;
  };
})();
